// add all the constants here

export const GET_CONSTANTS = {
    //Header constants
    'LOGO': 'Logo',
    'NAV_ICONS': 'Nav icons',
    'PROFILE': 'Profile',
    'MY_ACCOUNT': 'My account',
    'QUICK_ACCESS': 'Quick access',
    'NOTIFICATIONS': 'Notifications',
    'CLOSE': 'Close',

    //Sidebar constants
    'DASHBOARD': 'Dashboard',
    'UURROOSTER': 'Uurrooster',
    'MANAGE_PLANNINGS': 'Manage plannings',
    'EMPLOYEES': 'Manage employees',
    'COMPANIES': 'Manage companies',
    'CONFIGURATIONS': 'Configurations',
    'SETTINGS': 'Settings',
    'REPORTING': 'Reporting overview',

    //Dashboard constants
    'MESSAGE_BOARD': 'Message board',
    'EMPLOYEE_MESSAGE_TITLE': 'Message from employees',
    'INDII_MESSAGE_TITLE': 'Message from INDII',
    'DIMONA_MESSAGE_TITLE': 'Dimona failure',
    'PLANNING': 'Plannings',
    'TIME_TABLE': 'Time table',
    'AVAILABILITY': 'Employee availability',
    'NEW_EMPLOYEE': 'Create new employee',
    'QRCODE': 'Download QR code',
    'HOLIDAY': 'Manage holiday',
    'DIMONA': 'Dimona',
    'DEVICE_ACTIVATE': 'Device activate',

    // Companies overview constants
    'COMPANY': 'Company',
    'LOCATIONS': 'Locations',
    'WORKSTATION': 'Workstations',
    'RESP_PERSON': 'Responsible persons',
    'CONTRACTS': 'Contracts',
    'RESPONSIBLE_PERSONS': 'Responsible persons',
    'RULES': 'Rules',

    // employee creation tabs constants
    'PERSONAL_DETAILS': 'Personal details',
    'EMPLOYEE_CONTRACT_TYPE': 'Employee/Contract types',
    'FUNCTION_SALARIES': 'Function salaries',
    'TRANSPORTATION_DETAILS': 'Transportation details',
    'ADDITIONAL_INFO': 'Additional information',

    // Settings constants
    'ADD_FUNCTION': 'Add function',
    'ADD_EMPLOYEE_TYPE': 'Add employee type',
    'ADD_SECTOR': 'Add sector',
    'ADD_GROUP_FUNCTION': 'Add group function',
    'ADD_MIN_SALARY': 'Add minimum salaries',

    // Settings constant
    'GENDER': 'Gender',
    'MARITAL_STATUS': 'Marital status',
    'MEAL_VOUCHERS': 'Meal vouchers',
    'COMMUTE_TYPES': 'Commute types',

    // Configuration constant
    'FUNCTIONS': 'Functions',
    'EMPLOYEE_TYPES': 'Employee types',
    'SECTORS': 'Sectors',
    'GROUP_FUNCTIONS': 'Group functions',
    'MIN_SALARY': 'Minimum salaries',
    'CONTRACT_TYPE': 'Contract types',
    'REASONS': 'Reasons',
    'COST_CENTER': 'Cost center',
    'SOCIAL_SECRETARY': 'Social secretary',
    'INTERIM_AGENCIES': 'Interim agencies',

    // Planning Constants
    'OVERVIEW': 'Overview',
    'PLANNING_LOGS': 'Planning logs',
    'HOLIDAY_LEAVE': 'Holiday/leave',
    'EVENT_PLANNING': 'Event planning',

    // Days constants
    'MONDAY': 'Monday',
    'TUESDAY': 'Tuesday',
    'WEDNESDAY': 'Wednesday',
    'THURSDAY': 'Thursday',
    'FRIDAY': 'Friday',
    'SATURDAY': 'Saturday',
    'SUNDAY': 'Sunday',

    'WORKING_HOURS': 'Working hours',
    'LEAVE': 'Leave',

    // Login constants
    'USERNAME': 'Username',
    'PASSWORD': 'Password',
    'FORGOT_YOUR_PASSWORD': 'Forgot your password',
    'LOGIN': 'Login',
    'GET_LINK': 'Get Link',
    'BACK_LINK': 'Back',
    'FORGOT_PASSWORD_INSTRUCTION': 'Enter username below to get reset password link',
    'FORGOT_PASSWORD_SUCCESS_MESSAGE': 'Mail sent successfully. Please check your mail for reset password link',

    // Popup constants
    'RESPONSIBLE_COMPANY': 'Responsible company',
    'PLAN_DETAILS': 'Plan details',
    'YES': 'Yes',
    'ADD_LEAVE': 'ADD LEAVE',
    'HALF_DAY': 'Half day',
    'MULTIPLE_DAYS': 'Multiple days',
    'MULTIPLE_HOLIDAY_CODES': 'Multiple holiday codes',
    'MORNING': 'Morning',
    'EVENING': 'Evening',
    'MULTIPLE_DATES': 'Multiple dates',
    'HOLIDAY_CODE_FOR_MORNING_SHIFT': 'Holiday code for morning shift',
    'HOLIDAY_CODE_FOR_EVENING_SHIFT': 'Holiday code for evening shift',
    'REASON': 'Reason',
    'FROM_DATE': 'From date',
    'TO_DATE': 'To date',

    // My profile constants
    'MY_PROFILE': 'My profile',

    //Uurrooster constants
    'SELECT_LOCATION': 'Select location',
    'WS_TITLE': 'WS',
    'EMPLOYEE_TITLE': 'Employee',
    'FUNCTION_TITLE': 'Function',
    'START_WORK_TITLE': 'Start work',
    'PAUSE_TITLE': 'Pause',
    'END_WORK_TITLE': 'End work',
    'TOTAL_TITLE': 'Total',
    'PLANNING_TITLE': 'Planning',
    'STARTED_TITLE': 'Started',
    'STOPPED_TITLE': 'Stopped',
    'COST_TITLE': 'Cost',

    // Month constants
    'JANUARY': 'January',
    'FEBRUARY': 'February',
    'MARCH': 'March',
    'APRIL': 'April',
    'MAY': 'May',
    'JUNE': 'June',
    'JULY': 'July',
    'AUGUST': 'August',
    'SEPTEMBER': 'September',
    'OCTOBER': 'October',
    'NOVEMBER': 'November',
    'DECEMBER': 'December',
    'MONTH': 'Month',
    'WEEK': 'Week',
    'DAY': 'Day',

    // Planning overview constants
    'LOCATION': 'Location',
    'WORK_STATION': 'Workstation',
    'EMPLOYEE_TYPE': 'Employee type',
    'AVAILABILITY_TEXT': 'Show Availability for selected week',
    'PREFERRED_SHIFTS': 'Use preferred shifts',
    'IMPORT_PLANNING': 'Import planning',
    'CLONE_PLANNING': 'Clone planning',
    'CANCEL': 'Cancel',

    // Holiday/Leave constants
    'PENDING': 'Pending',
    'APPROVED': 'Approved',
    'REJECTED': 'Rejected',
    'CANCELLED': 'Cancelled',
    'APPLIED_DATE': 'Applied date',
    'MANAGER': 'Manager',
    'LEAVE_DATE': 'Leave date',
    'SELECT_DATE': 'Select date',
    'TITLE_TEXT': 'Title',
    'APPLIED_BY': 'Applied by',
    'REPORTING_MANAGER': 'Reporting manager',
    'REQUESTED_ON': 'Requested on',
    'APPLY': 'Apply',
    'RECENT': 'Recent',

    // Manage employees 
    'EMPLOYEES_TITLE': 'Employees',
    'CREATE_EMPLOYEE': 'Create employee',
    'EMAIL_FORWARD': 'Forward email',
    'FILTER': 'Filter',
    'EXPORT': 'Export',
    'MOBILE_NUMBER': 'Mobile number',
    'EMAIL_ADDRESS': 'Email address',
    'SSN': 'Social security number',
    'SEARCH_TEXT': 'Search',

    // Manage companies
    'ADD_COMPANY': 'Add company',
    'COMPANY_OVERVIEW': 'Company overview',
    'ADD_LOCATION': 'Add location',
    'ADD_WORKSTATION': 'Add workstation',
    'ADD_RESPONSIBLE_PERSON': 'Add responsible person',
    'ADD_COST_CENTER': 'Add cost center',
    'ADD_CONTRACT': 'Add contract',
    'PHONE_NUMBER': 'Phone number',
    'LOCATION_TITLE': 'Location',
    'ADDRESS_TITLE': 'Address',
    'STATUS_TEXT': 'Status',
    'SEQUENCE_NUMBER': 'Sequence number',
    'NAME_TEXT': 'Name',
    'ROLE': 'Role',
    'DELETE_CONFIRMATION_COMPANY': 'Are you sure you want to delete this item?',
    'WARNING_TITLE': 'Warning',
    'DETAILS': 'Details',
    'VIEW': 'View',
    'LINK_HOLIDAY_CODE': 'Link holiday code',
    'EDIT': 'Edit',
    'DELETE': 'Delete',
    'HOLIDAY_CODE': 'Holiday code',

    // Employee creation
    'VALIDATION_ERROR': 'Validation error!',
    'FIRST_NAME': 'First name',
    'LAST_NAME': 'Last name',
    'EMAIL': 'Email',
    'DATE_OF_BIRTH': 'DOB',
    'PLACE_OF_BIRTH': 'Place of birth',
    'LICENCE_EXPIRY': 'Licence expiry',
    'ADDRESS_STREET_HOUSE': 'Address: Street + House num',
    'POSTAL_CODE': 'Postal code',
    'CITY': 'City',
    'COUNTRY': 'Country',
    'NATIONALITY': 'Nationality',
    'BANK_ACCOUNT_NUMBER': 'Bank account number',
    'LANGUAGE': 'Language',
    'DEPENDANT_SPOUSE': 'Dependant spouse',
    'CHILDREN': 'Children',
    'SAVE': 'Save',
    'NEXT_LINK': 'Next',
    'PREV_LINK': 'Prev',

    // Employee contract types
    'WEEKLY_CONTRACT_HOURS': 'Weekly contract hours',
    'WORK_DAYS_PER_WEEK': 'Work days per week',
    'CONTRACT_START_DATE': 'Contract start date',
    'CONTRACTS_END_DATE': 'Contract end date',
    'SUB_TYPES': 'Sub types',
    'SCHEDULE_TYPE': 'Schedule type',
    'EMPLOYEEMENT_TYPE': 'Employement type',

    // Function salaries
    'EXPERIENCE': 'Experience',
    'MINIMUM_SALARY': 'Minimum salary',
    'SALARY_TO_BE_PAID': 'Salary to be paid',
    'ACTIONS': 'Actions',
    'DISTANCE_IN_KMS': 'Distance(kms)',
    'COMMUTE': 'Commute',
    'ADD_TEXT': 'Add',

    // Additional information
    'CONTRACT_NUMBER': 'Contract number',
    'COMPANY_FUEL_CARD': 'Company fuel card',
    'COMPANY_CAR': 'Company car',
    'CLOTHING_COMPENSATION': 'Clothing compensation(Euros)',
    'MEAL_VOUCHER_TYPE': 'Meal Voucher type',
    'MEAL_VOUCHER_AMOUNT': 'Meal Voucher amount',
    'ID_CARD_FRONT': 'Id card front',
    'ID_CARD_BACK': 'Id card back',
    'EXTRA_INFORMATION': 'Extra information',
    'EXTRA_BENEFITS': 'Extra benefits',
    'IDENTITY_INFO': 'Identity info',

    // Clone planning
    'CLONE_PLANNINGS': 'Clone plannings',
    'SELECT_WEEK_TO_COPY': 'Select a week to copy from',
    'SELECT_WEEK_TO_CLONE': 'Select a week to clone to',
    'CLONE': 'Clone',
    'FROM_YEAR': 'From year',
    'FROM_WEEK': 'From week',
    'TO_YEAR': 'To year',
    'TO_WEEK': 'To week',
    'EMPLOYEE_NAMES': 'Employee names',
    'CURRENT_WEEK': 'Current week',
    'WEEK_PLANNINGS_DELETE': 'Are you sure, you want to delete complete week plans?',

    'START_TIME': 'Start time',
    'END_TIME': 'End time',
    'ACTIVITIES': 'Activities',
    'VIEW_CONTRACT': 'View contract',
    'START_PLAN': 'Start plan',
    'STOP_PLAN': 'Stop plan',
    'TIME': 'Time',
    'START_TEXT': 'Start',
    'STOP_TEXT': 'Stop',
    'CALENDAR':'Calendar',
    'ICON':'Icon',
    'PREV_ARROW' :'Prev icon',
    'NEXT_ARROW' :'Next icon',

    // Add company
    'VAT_NUMBER':'VAT number',
    'COMPANY_NAME':'Company name',
    'SECTOR':'Sector',
    'SENDER_NUMBER':'Sender number',
    'RSZ_NUMBER':'RSZ number',
    'INTERIM_AGENCY':'Interim agency',
    'SECTOR_HOUSE_NUMBER':'Street and house number',
    'CONTACT_EMAIL':'Contact email',
    'SOCIAL_SECRETARY_DETAILS':'Social secretary details'
};