// add all the constants here

export const GET_CONSTANTS = {
    //Header constants
    'LOGO': 'Logo',
    'NAV_ICONS': 'Nav icons',
    'PROFILE': 'Profile',
    'MY_ACCOUNT': 'My account',
    'QUICK_ACCESS': 'Quick access',
    'NOTIFICATIONS': 'Notifications',
    'CLOSE': 'Close',

    //Sidebar constants
    'DASHBOARD': 'Dashboard',
    'UURROOSTER': 'Uurrooster',
    'MANAGE_PLANNINGS': 'Manage plannings',
    'EMPLOYEES': 'Manage employees',
    'COMPANIES': 'Manage companies',
    'CONFIGURATIONS': 'Configurations',
    'SETTINGS': 'Settings',
    'REPORTING': 'Reporting overview',

    //Dashboard constants
    'MESSAGE_BOARD': 'Message board',
    'EMPLOYEE_MESSAGE_TITLE': 'Message from employees',
    'INDII_MESSAGE_TITLE': 'Message from INDII',
    'DIMONA_MESSAGE_TITLE': 'Dimona failure',
    'PLANNING': 'Plannings',
    'TIME_TABLE': 'Time table',
    'AVAILABILITY': 'Employee availability',
    'NEW_EMPLOYEE': 'Create new employee',
    'QRCODE': 'Download QR code',
    'HOLIDAY': 'Manage holiday',
    'DIMONA': 'Dimona',
    'DEVICE_ACTIVATE': 'Device activate',

    // Companies overview constants
    'COMPANY': 'Company',
    'LOCATIONS': 'Locations',
    'WORKSTATION': 'Workstations',
    'RESP_PERSON': 'Responsible persons',
    'CONTRACTS': 'Contracts',
    'RESPONSIBLE_PERSONS': 'Responsible persons',
    'RULES': 'Rules',

    // employee creation tabs constants
    'PERSONAL_DETAILS': 'Personal details',
    'EMPLOYEE_CONTRACT_TYPE': 'Employee/Contract types',
    'FUNCTION_SALARIES': 'Function salaries',
    'TRANSPORTATION_DETAILS': 'Transportation details',
    'ADDITIONAL_INFO': 'Additional information',

    // Settings constants
    'ADD_FUNCTION': 'Add function',
    'ADD_EMPLOYEE_TYPE': 'Add employee type',
    'ADD_SECTOR': 'Add sector',
    'ADD_GROUP_FUNCTION': 'Add group function',
    'ADD_MIN_SALARY': 'Add minimum salaries',

    // Settings constant
    'GENDER': 'Gender',
    'MARITAL_STATUS': 'Marital status',
    'MEAL_VOUCHERS': 'Meal vouchers',
    'COMMUTE_TYPES': 'Commute types',

    // Configuration constant
    'FUNCTIONS': 'Functions',
    'EMPLOYEE_TYPES': 'Employee types',
    'SECTORS': 'Sectors',
    'GROUP_FUNCTIONS': 'Group functions',
    'MIN_SALARY': 'Minimum salaries',
    'CONTRACT_TYPE': 'Contract types',
    'REASONS': 'Reasons',
    'COST_CENTER': 'Cost center',
    'SOCIAL_SECRETARY': 'Social secretary',
    'INTERIM_AGENCIES': 'Interim agencies',
    'PARAMETER': 'Rules & parameters',

    // Planning Constants
    'OVERVIEW': 'Overview',
    'PLANNING_LOGS': 'Planning logs',
    'HOLIDAY_LEAVE': 'Holiday/leave',
    'EVENT_PLANNING':'Event planning',
    'OPEN_SHIFT':'Open shift',
    'DRAFTED': 'Drafted',
    'REPEAT': 'Repeat',
    'SIGN': 'Sign contract',
    'UPDATE':'Update',
    'CLEAR':'Clear',


    // Days constants
    'MONDAY': 'Monday',
    'TUESDAY': 'Tuesday',
    'WEDNESDAY': 'Wednesday',
    'THURSDAY': 'Thursday',
    'FRIDAY': 'Friday',
    'SATURDAY': 'Saturday',
    'SUNDAY': 'Sunday',

    'WORKING_HOURS': 'Working hours',
    'LEAVE': 'Leave',

    // Login constants
    'USERNAME': 'Username',
    'PASSWORD': 'Password',
    'FORGOT_YOUR_PASSWORD': 'Forgot your password',
    'LOGIN': 'Login',
    'GET_LINK': 'Get Link',
    'BACK_LINK': 'Back',
    'FORGOT_PASSWORD_INSTRUCTION': 'Enter username below to get reset password link',
    'FORGOT_PASSWORD_SUCCESS_MESSAGE': 'Mail sent successfully. Please check your mail for reset password link',

    // Popup constants
    'RESPONSIBLE_COMPANY': 'Responsible company',
    'PLAN_DETAILS': 'Plan details',
    'YES': 'Yes',
    'ADD_LEAVE': 'ADD LEAVE',
    'HALF_DAY': 'Half day',
    'MULTIPLE_DAYS': 'Multiple days',
    'MULTIPLE_HOLIDAY_CODES': 'Multiple holiday codes',
    'MORNING': 'Morning',
    'EVENING': 'Evening',
    'MULTIPLE_DATES': 'Multiple dates',
    'HOLIDAY_CODE_FOR_MORNING_SHIFT': 'Holiday code for morning shift',
    'HOLIDAY_CODE_FOR_EVENING_SHIFT': 'Holiday code for evening shift',
    'REASON': 'Reason',
    'FROM_DATE': 'From date',
    'TO_DATE': 'To date',

    // My profile constants
    'MY_PROFILE': 'My profile',
    'MY_ADDRESS': 'My address',
    'CHANGE_PASSWORD': 'Change password',
    'MY_BANK_ACCOUNT': 'My bank account',
    'BACK_TO_DASHBOARD': 'Back to Dashboard',
    'LOGOUT': 'Logout',
    "SIGNATURE_DETAILS":'Signature Details',

    //Uurrooster constants
    'SELECT_LOCATION': 'Select location',
    'WS_TITLE': 'WS',
    'EMPLOYEE_TITLE': 'Employee',
    'FUNCTION_TITLE': 'Function',
    'START_WORK_TITLE': 'Start work',
    'PAUSE_TITLE': 'Pause',
    'END_WORK_TITLE': 'End work',
    'TOTAL_TITLE': 'Total',
    'PLANNING_TITLE': 'Planning',
    'STARTED_TITLE': 'Started',
    'STOPPED_TITLE': 'Stopped',
    'COST_TITLE': 'Cost',

    // Month constants
    'JANUARY': 'January',
    'FEBRUARY': 'February',
    'MARCH': 'March',
    'APRIL': 'April',
    'MAY': 'May',
    'JUNE': 'June',
    'JULY': 'July',
    'AUGUST': 'August',
    'SEPTEMBER': 'September',
    'OCTOBER': 'October',
    'NOVEMBER': 'November',
    'DECEMBER': 'December',
    'MONTH': 'Month',
    'WEEK': 'Week',
    'DAY': 'Day',

    // Planning overview constants
    'LOCATION': 'Location',
    'WORK_STATION': 'Workstation',
    'EMPLOYEE_TYPE': 'Employee type',
    'AVAILABILITY_TEXT': 'Show Availability for selected week',
    'PREFERRED_SHIFTS': 'Use preferred shifts',
    'IMPORT_PLANNING': 'Import planning',
    'CLONE_PLANNING': 'Clone planning',
    'CANCEL': 'Cancel',

    // Holiday/Leave constants
    'PENDING':'Pending',
    'APPROVED':'Approved',
    'REJECTED':'Rejected',
    'CANCELLED':'Cancelled',
    'APPLIED_DATE':'Applied date',
    'MANAGER':'Manager',
    'LEAVE_DATE':'Leave date',
    'SELECT_DATE':'Select date',
    'TITLE_TEXT':'Title',
    'APPLIED_BY':'Applied by',
    'REPORTING_MANAGER':'Reporting manager',
    'REQUESTED_ON':'Requested on',
    'APPLY':'Apply',
    'RECENT':'Recent',

    // Oth Planning
    'OTH_TITLE': 'Oth auto planning',
    'CREATE_OTH': 'Create oth plans',
    'ADD_OTH':'Add Oth auto planning',
    'RENEW_OTH':"Renew plans automatically",
    'DELETE_OTH_WARNING': 'Are you sure, you want to delete this oth plan?',
    'REPETATION': 'Repetation',

    // Manage employees 
    'EMPLOYEES_TITLE': 'Employees',
    'CREATE_EMPLOYEE': 'Create employee',
    'EMAIL_FORWARD': 'Forward email',
    'FILTER': 'Filter',
    'EXPORT': 'Export',
    'MOBILE_NUMBER': 'Mobile number',
    'EMAIL_ADDRESS': 'Email address',
    'SSN': 'Social security number',
    'SEARCH_TEXT': 'Search',
    'SOCIAL_SECRETARY_NUMBER': 'Social secretary number',
    'DOCUMENT_NAME':'Document name',
    'INVITE_EMPLOYEE':'Invite employee',
    'SEND':'send',

    // Manage companies
    'ADD_COMPANY': 'Add company',
    'COMPANY_OVERVIEW': 'Company overview',
    'ADD_LOCATION': 'Add location',
    'ADD_WORKSTATION': 'Add workstation',
    'ADD_RESPONSIBLE_PERSON': 'Add responsible person',
    'ADD_COST_CENTER': 'Add cost center',
    'ADD_CONTRACT': 'Add contract',
    'PHONE_NUMBER': 'Phone number',
    'LOCATION_TITLE': 'Location',
    'ADDRESS_TITLE': 'Address',
    'STATUS_TEXT': 'Status',
    'SEQUENCE_NUMBER': 'Sequence number',
    'NAME_TEXT': 'Name',
    'ROLE': 'Role',
    'DELETE_CONFIRMATION_COMPANY': 'Are you sure you want to delete this item',
    'WARNING_TITLE': 'Warning',
    'DETAILS': 'Details',
    'VIEW': 'View',
    'LINK_HOLIDAY_CODE': 'Link holiday code',
    'EDIT': 'Edit',
    'DELETE': 'Delete',
    'HOLIDAY_CODE': 'Holiday code',
    'OAUTH_KEY':'Oauth key',

    // Employee creation
    'VALIDATION_ERROR': 'Validation error!',
    'FIRST_NAME': 'First name',
    'LAST_NAME': 'Last name',
    'EMAIL': 'Email',
    'DATE_OF_BIRTH': 'DOB',
    'PLACE_OF_BIRTH': 'Place of birth',
    'LICENCE_EXPIRY': 'Licence expiry',
    'ADDRESS_STREET_HOUSE': 'Address: Street + House num',
    'POSTAL_CODE': 'Postal code',
    'CITY': 'City',
    'COUNTRY': 'Country',
    'NATIONALITY': 'Nationality',
    'BANK_ACCOUNT_NUMBER': 'Bank account number',
    'LANGUAGE': 'Language',
    'DEPENDANT_SPOUSE': 'Dependant spouse',
    'CHILDREN': 'Children',
    'SAVE': 'Save',
    'NEXT_LINK': 'Next',
    'PREV_LINK': 'Prev',
    'CONTRACT_DETAILS': 'Contract details',
    'COUNTERS': 'Counters',
    'DOCUMENTS': 'Documents',
    'EMPLOYEE_AVAILABILITY': 'Availability',
    'EXPIRY_DATE': 'Expiry date',
    'SUB_TYPE': 'Sub type',
    'START_DATE': 'Start date',
    'END_DATE': 'End date',
    'FUNCTION_NAME': 'Function name',
    'SALARY': 'Salary',
    'TYPE': 'Type',
    'OK': 'Ok',
    'CREATE': 'Create',
    'PAST_CONTRACTS': 'Past contracts',
    'HOLIDAY_COUNTER': 'Holidays counter',
    'EXT_COUNTER': 'EXT counter',
    'EMPLOYEE_CONTRACT_TYPES': 'Contract type',
    'PUBLIC': 'Public',
    'OPTIONAL': 'Optional',
    'USED_TITLE': 'Used',
    'REMAINING_TITLE': 'Remaining',
    'STREET_HOUSE': 'Street+house no',

    // Employee contract types
    'WEEKLY_CONTRACT_HOURS': 'Weekly contract hours',
    'WORK_DAYS_PER_WEEK': 'Work days per week',
    'CONTRACT_START_DATE': 'Contract start date',
    'CONTRACTS_END_DATE': 'Contract end date',
    'SUB_TYPES': 'Sub types',
    'SCHEDULE_TYPE': 'Schedule type',
    'EMPLOYEEMENT_TYPE': 'Employement type',

    // Function salaries
    'EXPERIENCE': 'Experience',
    'MINIMUM_SALARY': 'Minimum salary',
    'SALARY_TO_BE_PAID': 'Salary to be paid',
    'ACTIONS': 'Actions',
    'DISTANCE_IN_KMS': 'Distance(kms)',
    'COMMUTE': 'Commute',
    'ADD_TEXT': 'Add',

    // Additional information
    'CONTRACT_NUMBER': 'Contract number',
    'COMPANY_FUEL_CARD': 'Company fuel card',
    'COMPANY_CAR': 'Company car',
    'CLOTHING_COMPENSATION': 'Clothing compensation(Euros)',
    'MEAL_VOUCHER_TYPE': 'Meal Voucher type',
    'MEAL_VOUCHER_AMOUNT': 'Meal Voucher amount',
    'ID_CARD_FRONT': 'Id card front',
    'ID_CARD_BACK': 'Id card back',
    'EXTRA_INFORMATION': 'Extra information',
    'EXTRA_BENEFITS': 'Extra benefits',
    'IDENTITY_INFO': 'Identity info',
    'CLOTHING_COMPENSAT': 'Clothing compensation',
    'MEAL_VOUCHER': 'Meal Voucher',

    // Clone planning
    'CLONE_PLANNINGS': 'Clone plannings',
    'SELECT_WEEK_TO_COPY': 'Select a week to copy from',
    'SELECT_WEEK_TO_CLONE': 'Select a week to clone to',
    'CLONE': 'Clone',
    'FROM_YEAR': 'From year',
    'FROM_WEEK': 'From week',
    'TO_YEAR': 'To year',
    'TO_WEEK': 'To week',
    'EMPLOYEE_NAMES': 'Employee names',
    'CURRENT_WEEK': 'Current week',
    'WEEK_PLANNINGS_DELETE': 'Are you sure, you want to delete complete week plans?',

    'START_TIME': 'Start time',
    'END_TIME': 'End time',
    'ACTIVITIES': 'Activities',
    'VIEW_CONTRACT': 'View contract',
    'START_PLAN': 'Start plan',
    'STOP_PLAN': 'Stop plan',
    'TIME': 'Time',
    'START_TEXT': 'Start',
    'STOP_TEXT': 'Stop',
    'CALENDAR': 'Calendar',
    'ICON': 'Icon',
    'PREV_ARROW': 'Prev icon',
    'NEXT_ARROW': 'Next icon',

    // Add company
    'VAT_NUMBER': 'VAT number',
    'COMPANY_NAME': 'Company name',
    'SECTOR': 'Sector',
    'SENDER_NUMBER': 'Sender number',
    'RSZ_NUMBER': 'RSZ number',
    'INTERIM_AGENCY': 'Interim agency',
    'SECTOR_HOUSE_NUMBER': 'Street and house number',
    'CONTACT_EMAIL': 'Contact email',
    'SOCIAL_SECRETARY_DETAILS': 'Social secretary details',
    'ROLES': 'Roles',
    'REMOVE': 'Remove',
    'ADD_ANOTHER': 'Add another',
    'SAME_AS_COMPANY_ADDRESS': 'Same as company address',
    'SKIP_LINK': 'Skip',
    'WORKSTATION_NAME': 'Workstation name',
    'ACTIVE': 'Active',
    'INACTIVE': 'Inactive',
    'COST_CENTER_NUMBER': 'Cost center number',
    'PLEASE_FILL_REQUIRED_FIELDS': 'Please fill required fields',
    'PREVIEW_TEXT': 'Preview',
    'DESCRIPTION': 'Description',
    'ADD_CONTRACT_TEMPLATE': ' Add contract template',
    'TOKENS': 'Tokens',
    'COMPANY_DETAILS': 'Company details',
    'SECTOR_NAME': 'Sector name',

    // Configuration
    'EMPLOYEE_CONFIGURATIONS': 'Employee configurations',
    'HOLIDAY_CODES': 'Holiday codes',
    'HOLIDAY_CODE_CONFIGURATION': 'Holiday code configuration',
    'EMAIL_TEMPLATES': 'Email templates',
    'TRANSLATIONS': 'Translations',
    'CONTRACT_TEMPLATES': 'Contract templates',
    'HOLIDAY_CONFIGURATION': 'Holiday configurations',
    'COMMUNICATION_CONFIGURATION': 'Communication configuration',
    'GROUP_FUNCTION_TITLE': 'Group function title',
    'CATEGORY': 'Category',
    'MANAGE_SECTORS': 'Manage sectors',
    'MANAGE_EMPLOYEE_TYPES': 'Manage employee types',
    'MANAGE_FUNCTIONS': 'Manage functions',
    'MANAGE_GROUP_FUNCTION': 'Manage group functions',
    'MANAGE_CONTRACT_TYPES': 'Manage contract types',
    'ADD_CONTRACT_TYPE': 'Add contract type',
    'MANAGE_REASONS': 'Manage reasons',
    'ADD_REASONS': 'Add reasons',
    'MANAGE_SOCIAL_SECRETARY': 'Manage social secretary',
    'ADD_SOCIAL_SECRETARY': 'Add social secretary',
    'MANAGE_INTERIM_AGENCIES': 'Manage interim agencies',
    'ADD_INTERIM_AGENCIES': 'Add interim agencies',
    'PUBLIC_HOLIDAY_CONFIGURATION':'Public holiday configuration',
    'MANAGE_PUBLIC_HOLIDAY':'Manage public holiday',
    'ADD_PUBLIC_HOLIDAY':'Add public holiday',
    'HOLIDAY_NAME':'Holiday name',
    'DATE':'date',

    // Add employee type
    'EMPLOYEE_TYPE_NAME': 'Employee type name',
    'EMPLOYEE_TYPE_CATEGORY': 'Employee type category',
    'DIMONA_TYPE': 'Dimona type',
    'DIMONA_CODE': 'Dimona Code',
    'CONSECUTIVE_DAY_LIMIT': 'Consecutive days limit',
    'SALARY_TYPE': 'Salary type',
    'START_IN_PAST': 'Start in past',
    'CONTRACT_HOURS_SPLIT': 'Contract hours split',
    'LEAVE_ACCESS': 'Leave access',
    'HOLIDAY_ACCESS': 'Holiday access',
    'ICON_COLOR': 'Icon color',
    'HOURS': 'Hours',

    // Add contract type
    'CONTRACT_TYPE_NAME': 'Contract type name',
    'CONTRACT_RENEWAL_PERIOD': 'Contract renewal period',

    // Add sectors
    'ADD_SECTORS': 'Add Sectors',
    'LEVEL': 'Level',
    'EXPERIENCE_RANGE': 'Experience range (in months)',
    'AGE': 'Age',
    'SALARY_PERCENTAGE': 'Salary percentage',
    'MAX_TIME': 'MaxTime',
    'INFORMATION': 'Information',
    'ENTER_SECTOR_NAME': 'Enter sector name',
    'PARITAIR_COMMITTEE': 'Paritair committee',
    'ENTER_PARITAIR_COMMITTEE': 'Enter paritair committee',
    'NUMBER_OF_CATEGORIES': 'Number of categories',
    'NIGHT_SHIFT_START_TIME': 'Night shift start time',
    'NIGHT_SHIFT_END_TIME': 'Night shift end time',
    'FUNCTION_TEXT': 'Function title',
    'ENTER_FUNCTION_TITLE': 'Enter function title',
    'FUNCTION_CODE': 'Function code',
    'ENTER_FUNCTION_CODE': 'Enter function code',
    'FUNCTION_CATEGORIES': 'Function categories',
    'FUNCTION_DESCRIPTION': 'Function description',

    // Group function
    'GROUP_FUNCTION_NAME': 'Group function name',
    'ENTER_FUNCTION_NAME': 'Enter function name',
    'FUNCTION_CATEGORY': 'Function category',
    'SUCCESS': 'Success',
    'MONTHLY': 'Monthly',
    'HOURLY': 'Hourly',
    'INCREMENT_COEFFIFICENT_NEW_MMINIMUM_SALARIES': 'Please enter the increment coefficent to check and confirm new minimum salaries',
    'INCREASE_MINIMUM_SALARIES': 'Increase minimum salaries',
    'MANAGE_MINIMUM_SALARIES': 'Manage minimum salaries',
    'INCREMENT_COEFFICIENT': 'Increment coefficient',
    'CHECK_TEXT': 'Check',
    'GET_SALARIES': 'Get salaries',
    'UNDO': 'Undo',
    'CONFIRMATION_SLARIES_REVERT_BACK': 'Are you sure you want to revert back the salaries',
    'INCREMENT_SALARIES': 'Increment salaries',
    'SELECT_SECTOR_SALARY_TYPE': 'Please select sector and salary type to get the salaries',

    // Add reasons
    'REASON_NAME': 'Reason name',
    // Social secretary
    'SOCIAL_SECRETARY_NAME': 'Social secretary name',
    'HOLIDAY_CODE_NAME': 'Holiday code name',
    'INETRNAL_CODE': 'Internal code',
    'SOCIAL_SECRETARY_CODE': 'Social secretary code',
    'COMPANIES_TEXT': 'Companies',
    'EMPLOYER_ID': 'Employer id',
    'JOINT_COMMISSIONER_NUMBER': 'Joint commissioner number',
    'ADD_INTERIM_AGENCY': 'Add Interim agency',

    // Manage holiday
    'MANAGE_HOLIDAY_CODE': 'Manage holiday code',
    'ADD_HOLIDAY_CODE': 'Add holiday code',
    'MANAGE_HOLIDAY_CODE_CONFIGURATION': 'Manage holiday code configuration',
    'SELECT_COMPANY': 'Select company',
    'SELECT': 'Select',
    'COMPANY_TEXT': 'Company',
    'HOLIDAY_TYPE': 'Holiday type',
    'COUNT_TYPE': 'Count type',
    'EMPLOYEE_CATEGORY': 'Employee category',
    'ICON_TYPE': 'Icon type',
    'COUNT': 'Count',
    'ALL': 'All',
    'INCLUDE': 'Include',
    'EXCLUDE': 'Exclude',
    'LINK_COMPANIES': 'Link companies',
    'PLAN_HOURS_IN_WEEKLY_HOURS': 'Consider the plan hours in weekly hours',

    // Email templates
    'STRING': 'String',
    'MANAGE_EMAIL_TEMPLATE': 'Manage email templates',
    'MANAGE_CONTRACTS_TEMPLATE': 'Manage contracts templates',
    'CREATE_CONTRACTS_TEMPLATE': 'Create contracts template',
    'MANAGE_TRANSLATIONS': 'Manage translations',
    'SUBJECT': 'Subject',
    'PREVIEW': 'Preview',
    'ADD_EMAIL_TEMPLATE': 'Add Email template',
    'MANAGE_GENDERS': 'Manage Genders',
    'SORT_ORDER': 'Sort order',
    'AMOUNT_TEXT': 'Amount',

    'STREET': 'Street',
    'HOUSE_NUMBER': 'House Number',
    'BOX_NUMBER': 'Box Number',
    'NO_ENTRIES_TO_SHOW': 'No entries to show',
    'PASSWORD_GUIDELINES': 'Password should contain minimum 8 characters, with one UPPERCASE, lowercase, number and special character',
    'STRONG_PASSWORD': 'Strong password',
    'WEAK_PASSWORD': 'Weak passoword',
    'PASSWORD_NOT_MATCHING': 'Confirm password not matching with new password',
    'RESET_PASSWORD': 'Reset Password',
    'NEW_PASSWORD': 'New Password',
    'CONFIRM_PASSWORD': 'Confirm Password',
    "PHOTO_OF_BANK_ACCOUNT": "Photo of bank account",
    'UPLOAD_PHOTO': 'Upload photo',
    'ENABLE_NOTIFICATION': 'Enable Notification',
    'ENABLE_EMAIL_NOTIFICATION': 'Enable Email Notification',
    'REQUIRED': 'Required',
    'SELECT_FOR_MULTIPLE_PLANNINGS': 'Select for multiple plannings',
    'CONTRACT_HOURS': 'Contract hours',
    'ADD_PLANNING': "Add planning",
    'ADD_EDIT_SHIFTS': 'Add/Edit Shifts',
    'DRAG': 'Drag',
    'DROP_YOUR_FILES': 'Drop your files',
    'BROWSE': 'Browse',
    'OR': 'or',
    'CHOOSE_A_FILE': 'Choose a file',
    'CHANGE_COMPANY': 'Change company',
    'ADD_EMPLOYEE': 'Add employee',
    'ADD_HOLIDAYS': 'Add holidays',
    'SEND_INVOICES': 'Send invoices',
    'PLEASE_SELECT_RESPONSIBLE_COMPANY':'Please select responsible company'

};